.

diff --git a/.github/workflows/docker-build-test.yml b/.github/workflows/docker-build-test.yml
--- a/.github/workflows/docker-build-test.yml
+++ b/.github/workflows/docker-build-test.yml
@@ -2,18 +2,17 @@ jobs:
   build-test-push:
     runs-on: ubuntu-latest
 
-    services:
-      db:
-        image: nouchka/sqlite # image sqlite temporaire
-        volumes:
-          - /data:/app/data
-        ports:
-          - 8000:8000
-        options: --entrypoint ""
-
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
+
+    - name: Verify presence of ts_meteo.db
+      run: |
+        if [ ! -f ./data/ts_meteo.db ]; then
+          echo "ts_meteo.db is missing!"
+          exit 1
+        fi
+        echo "ts_meteo.db found"
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
